import type { Metadata } from "next";
import { ClerkProvider } from '@clerk/nextjs'
import localFont from "next/font/local";
import "./globals.css";
import TopNav from "@/components/nav/top-nav";
import MobileNav from "@/components/nav/mobile-nav";
import SideNav from "@/components/nav/side-nav";
import { ThemeProvider } from "@/components/theme-provider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased h-screen`}
        >
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <header><TopNav /></header>
            <main className='flex'>
              <div className='hidden md:block w-1/4 h-full'>
                <SideNav />
                <div className='md:hidden w-full'>
                  <MobileNav />
                </div>
              </div>
              <div className='flex-1 overflow-y-hidden h-full'>{children}</div>
            </main>
            {/* <footer className="absolute bottom-0 text-center left-2 right-2">
              <p className="text-sm text-gray-500">
                &copy; {new Date().getFullYear()}  AI Images Tools. All rights
              </p>
            </footer> */}
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
